version: "3"
services:
  calculator-api-redis:
    image: "redis:latest"
    container_name: "calculator-api-redis"
    ports:
      - 6379:6379
    hostname: calculator-api-redis
  calculator-api-app:
    build:
      context: .
    ports:
      - 8080:8080
      - 8081:8081
      - 3030:3030
    container_name: calculator-api-app
    depends_on:
      - calculator-api-redis
  calculator-api-gateway:
    image: calculator-gateway.jar:latest
    build:
      context: .
    ports:
      - 9000:9000
    expose:
      - 9000
    container_name: calculator-api-gateway
    depends_on:
      - calculator-api-redis
  calculator-api-prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
    container_name: calculator-api-prometheus
  calculator-api-grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    depends_on:
      - calculator-api-prometheus
    container_name: calculator-api-grafana