version: "3"
services:
  mysql:
    image: redis:latest
    container_name: calculator-redis
    restart: always
    ports:
      - 6379
    expose:
      - 6379
  calculator:
    build:
      context: .
    ports:
      - 8080:8080
      - 8081:8081
    container_name: calculator-container