global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "jmx_prometheus_javaagent"
    static_configs:
      - targets: ["calculator-api-app:3030"]
